### ISSUE TITLE
Remove my commit pls

### ISSUE THREAD

**Issue by Eventretta** [ShadowMilky/FNF-Unfulfilled-Journey#20]
### What is your question?

remove stage editor pls

**Comment by ShadowMilky** [comment]
i already credited you in the readme in the other repo
so maybe i should just remake the stage editor myself instead

**Comment by ShadowMilky** [comment]
![B0FB449A-10DA-49E8-BA04-0978E7234D84](https://user-images.githubusercontent.com/62410083/200645210-19fb3ec4-6a60-41c2-a2e2-23001f3d526b.jpeg)
look i already credited you in the read me

**Comment by ShadowMilky** [comment]
but im probably gonna try to remake the stage editor anyway soooo
